apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-ingress
  namespace: amani
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx       # ‚Üê Add this line
  tls:
    - hosts:
        - amani.terrasofthq.com
      secretName: amani-tls
  rules:
    - host: amani.terrasofthq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: 80
